name: Auto Changelog

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken, inklusive aller Branch-Referenzen
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          # Git-Historie und alle Branches auschecken
          fetch-depth: 0

      # Hole die Basis- und Ziel-Branch-Informationen
      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }}

      # Commits mit `#` filtern
      - name: Get commits with `#`
        run: |
          # Hole die Commits im Pull Request (vom base Branch bis zum aktuellen Branch)
          COMMITS=$(git log origin/${{ github.base_ref }}..HEAD --oneline)

          # Filtere Commits, die mit `#` beginnen, und unterdrücke Fehler, falls keine Commits gefunden werden
          CHANGES=$(echo "$COMMITS" | grep '^#' || true)

          # Falls keine Commits gefunden werden, beende den Prozess
          if [ -z "$CHANGES" ]; then
            echo "No commits with '#' found."
            exit 0
          fi

          # Falls changelog.json nicht existiert, erstelle die Datei
          if [ ! -f changelog.json ]; then
            echo "[]" > changelog.json
          fi

          # Füge neue Änderungen zur changelog.json hinzu
          echo "$CHANGES" | jq -R -s -c 'split("\n")[:-1] | map({"commit": .})' > new_changes.json
          jq -s '.[0] + .[1]' changelog.json new_changes.json > updated_changelog.json
          mv updated_changelog.json changelog.json

      # Änderungen an changelog.json commiten und pushen
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add changelog.json
          git commit -m "Update changelog.json with new changes"
          git push
