name: Auto Changelog

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken, inklusive aller Branch-Referenzen
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Überprüfe die Verfügbarkeit des Basis-Branches
      - name: Fetch base branch
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}

      # Commits mit `#` filtern
      - name: Get commits with `#`
        id: get_commits
        run: |
          # Hole die Commits im Pull Request (vom base Branch bis zum aktuellen Branch)
          echo "Fetching commits between origin/${{ github.base_ref }} and HEAD"
          COMMITS=$(git log origin/${{ github.base_ref }}..HEAD --oneline)
          echo "Commits found:"
          echo "$COMMITS"

          # Filtere Commits, die mit `#` beginnen
          CHANGES=$(echo "$COMMITS" | grep '^#' || true)
          echo "Filtered commits with '#':"
          echo "$CHANGES"

          # Falls keine Commits gefunden werden, beende den Prozess
          if [ -z "$CHANGES" ]; then
            echo "No commits with '#' found."
            echo "changes=[]" >> $GITHUB_ENV
            exit 0
          fi

          # Speichern der gefilterten Commits als Umgebungsvariable
          JSON_CHANGES=$(echo "$CHANGES" | jq -R -s -c 'split("\n")[:-1] | map({"commit": .})')
          echo "changes=$JSON_CHANGES" >> $GITHUB_ENV
          echo "Changes JSON: $JSON_CHANGES"  # Debugging-Zeile

      # Falls changelog.json nicht existiert, erstelle die Datei
      - name: Create changelog.json if it does not exist
        run: |
          if [ ! -f changelog.json ]; then
            echo "Creating changelog.json"
            echo "[]" > changelog.json
          fi

      # Füge neue Änderungen zur changelog.json hinzu
      - name: Update changelog.json with new changes
        run: |
          echo "Appending new changes to changelog.json"
          echo "${{ env.changes }}" > new_changes.json
          echo "New changes JSON: $(cat new_changes.json)"  # Debugging-Zeile
          jq -s '.[0] + .[1]' changelog.json new_changes.json > updated_changelog.json
          mv updated_changelog.json changelog.json
          echo "Updated changelog.json:"
          cat changelog.json

      # Änderungen an changelog.json commiten und pushen
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add changelog.json
          git commit -m "Update changelog.json with new changes" || echo "No changes to commit"
          git push
