name: Auto Changelog

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken, inklusive aller Branch-Referenzen
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Checkout des aktuellen PR-Branches
      - name: Checkout the current PR branch
        run: |
          git checkout ${{ github.head_ref }}

      # Commits mit `#` filtern
      - name: Get commits with `#`
        id: get_commits
        run: |
          # Hole die Commits im Pull Request (vom base Branch bis zum aktuellen Branch)
          echo "Fetching commits between ${{ github.event.pull_request.base.sha }} and ${{ github.sha }}"
          COMMITS=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.sha }} --oneline)
          echo "Commits found:"
          echo "$COMMITS"

          # Filtere Commits, die mit `#` beginnen, und erlaube Leerzeichen davor
          CHANGES=$(echo "$COMMITS" | grep '^\s*#' || true)
          echo "Filtered commits with '#':"
          echo "$CHANGES"

          # Falls keine Commits gefunden werden, beende den Prozess
          if [ -z "$CHANGES" ]; then
            echo "No commits with '#' found."
            exit 0
          fi

          # Speichern der gefilterten Commits als Umgebungsvariable
          echo "CHANGES<<EOF" >> $GITHUB_ENV
          echo "$CHANGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Überprüfe den Inhalt der Umgebungsvariable 'CHANGES'
      - name: Debug - Check CHANGES environment variable
        run: |
          echo "Debugging - Checking filtered commits:"
          echo "${{ env.CHANGES }}"

      # Falls CHANGELOG.md nicht existiert, erstelle die Datei
      - name: Create CHANGELOG.md if it does not exist
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "Creating CHANGELOG.md"
            echo "# Changelog" > CHANGELOG.md
          fi
          cat CHANGELOG.md

      # Füge neue Änderungen zur CHANGELOG.md hinzu
      - name: Update CHANGELOG.md with new changes
        run: |
          echo "Appending new changes to CHANGELOG.md"
          echo "${{ env.CHANGES }}" >> CHANGELOG.md
          echo "Updated CHANGELOG.md:"
          cat CHANGELOG.md

      # Änderungen an CHANGELOG.md commiten und pushen
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md with new changes"
          git push origin ${{ github.head_ref }}
