name: Generate Changelog and Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      # Checkout des Repositories
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Installiere Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Aktualisiere auf eine unterstützte Version

      # Installiere release-it
      - name: Install release-it
        run: |
          npm install -g release-it

      # Generiere CHANGELOG.md
      - name: Generate CHANGELOG.md
        run: |
          release-it --no-ci --dry-run  # Führe release-it im "dry-run" Modus aus, um zu testen

      # Commit und Push der Änderungen an CHANGELOG.md
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Überprüfen, ob CHANGELOG.md geändert wurde
          if [ -f CHANGELOG.md ]; then
            git add CHANGELOG.md
            # Überprüfen, ob Änderungen vorhanden sind
            if ! git diff-index --quiet HEAD --; then
              git commit -m "Update CHANGELOG.md [skip ci]"
              git push origin HEAD:master
            else
              echo "No changes to CHANGELOG.md, skipping commit."
            fi
          else
            echo "CHANGELOG.md does not exist, skipping commit."
          fi

      # Deployment zu GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Stelle sicher, dass CHANGELOG.md im Hauptverzeichnis ist
          publish_branch: master  # Pushen in den master Branch
