name: Generate Changelog and Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      # Checkout des Repositories
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Verwende die Conventional Changelog Action
      - name: Generate CHANGELOG.md
        id: changelog
        uses: conventional-changelog/standard-version@9.3.2
        with:
          skip: true  # Setze dies auf true, wenn du die Version nicht erhöhen möchtest
          token: ${{ secrets.GITHUB_TOKEN }}
        
      # Commit und Push der Änderungen an CHANGELOG.md
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          if [ -f CHANGELOG.md ]; then
            git add CHANGELOG.md
            git commit -m "Update CHANGELOG.md [skip ci]"
            git push origin HEAD:master
          else
            echo "CHANGELOG.md does not exist, skipping commit."
          fi

      # Deployment zu GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Stelle sicher, dass CHANGELOG.md im Hauptverzeichnis ist
          publish_branch: master  # Pushen in den master Branch
