name: Auto Changelog and Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      # Checkout des Repositories
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Commits mit `#` filtern und CHANGELOG.md aktualisieren
      - name: Get commits with `#` and update CHANGELOG.md
        id: update_changelog
        run: |
          echo "Fetching commits"
          COMMITS=$(git log origin/master..HEAD --oneline)
          CHANGES=$(echo "$COMMITS" | grep '^#' || true)

          if [ -z "$CHANGES" ]; then
            echo "No commits with '#' found."
            echo "::set-output name=changes::No changes to update"
            exit 0
          fi

          echo "Updating CHANGELOG.md"
          echo "# Changelog" > CHANGELOG.md
          echo "$CHANGES" | sed 's/^#/- /' >> CHANGELOG.md

          echo "::set-output name=changes::$(cat CHANGELOG.md)" # Ausgabe für den nächsten Schritt

      # Debugging: Verzeichnisinhalt auflisten
      - name: List directory contents
        run: |
          echo "Current directory contents:"
          ls -al

      # Commit und Push der Änderungen an CHANGELOG.md
      - name: Commit changes
        if: steps.update_changelog.outputs.changes != 'No changes to update'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md [skip ci]"
          git push origin HEAD:master # Push in den master Branch

      # Deployment zu GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Hauptverzeichnis, wo CHANGELOG.md gespeichert ist
          publish_branch: master  # Pushen in den master Branch
