name: Generate Changelog

on:
  pull_request:
    types: [closed]
    branches:
      - master

concurrency:
  group: "changelog-and-pages"
  cancel-in-progress: true

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Extract commits from the pull request
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}

          echo "Pull Request Number: $PR_NUMBER"
          echo "Source Branch: $SOURCE_BRANCH"

          COMMITS=$(git log --pretty=format:"%H %s" --grep '^#' origin/${SOURCE_BRANCH})

          if [ -z "$COMMITS" ]; then
            echo "No commits found with #. Exiting."
            exit 0
          fi

          echo "{
            \"pull_request\": $PR_NUMBER,
            \"commits\": [" > changelog.json

          while IFS= read -r line; do
            HASH=$(echo $line | cut -d ' ' -f 1)
            MESSAGE=$(echo $line | cut -d ' ' -f 2-)
            echo "  {\"hash\": \"$HASH\", \"message\": \"$MESSAGE\"}," >> changelog.json
          done <<< "$COMMITS"

          echo "]
          }" >> changelog.json

      - name: Commit and push the changelog.json file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add changelog.json
          git commit -m "Update changelog.json with PR #${{ github.event.pull_request.number }}"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
