name: Generate Changelog

on:
  pull_request:
    branches: [ master ]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Changelog
        run: node index.js
