name: Sync Changelog to Development Branch

on:
  push:
    branches:
      - master

jobs:
  sync_changelog:
    runs-on: ubuntu-latest
    name: Sync Changelog to Development

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Holt das gesamte Repository mit allen Branches

    - name: Pull latest changes from master
      run: |
        git fetch origin
        git checkout master
        git pull origin master

    - name: Checkout Development Branch and Merge Changelog
      run: |
        git checkout development
        git merge master --no-edit

    - name: Push Changelog to Development
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin development
