name: Generate Changelog

on:
  pull_request:
    branches: [ master ]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install @octokit/rest
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install @octokit/rest
      - name: Generate Changelog
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { paginate } = require('@octokit/rest');
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = pr.base.ref;
            const head = pr.head.ref;

            // ... rest of your script
