name: Generate Changelog

on:
  pull_request:
    branches: [ master ]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Changelog
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = pr.base.ref;
            const head = pr.head.ref;

            const commits = context.github.paginate.iterator(
              context.github.repos.compareCommits,
              {
                owner,
                repo,
                base,
                head,
              }
            );

            let changelog = "# Changelog\n\n";
            for await (const commit of commits) {
              changelog += `* ${commit.data.sha}: ${commit.data.commit.message}\n`;
            }

            await github.rest.repos.createOrUpdateFileContents({
              owner,
              repo,
              path: 'CHANGELOG.md',
              message: 'Update changelog',
              content: Buffer.from(changelog).toString('base64'),
              sha: 'main', // Ersetze 'main' durch den SHA des aktuellen CHANGELOG.md, falls vorhanden
            });
