name: Generate Changelog

on:
  pull_request:
    types: [merged]
    branches: [master]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate changelog
        run: |
          # Hole die Commit-Informationen des gemergten PRs (hier musst du die API-Aufrufe anpassen)
          commits=$(curl -s https://api.github.com/repos/<owner>/<repo>/pulls/$PULL_REQUEST_NUMBER/commits)
          # Parse die JSON-Antwort und extrahiere die benötigten Informationen
          # ...
          # Füge die Commit-Informationen im Markdown-Format zur changelog.md hinzu
          echo "# Changelog" >> changelog.md
          for commit in $(echo $commits | jq -r '.[] | "\(.commit.sha) - \(.commit.message)"'); do
            echo "$commit" >> changelog.md
          echo "" >> changelog.md
          done
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add changelog.md
          git commit -m "Update changelog"
          git push
