# GitHub Actions for Changelog Generation

name: Generate Changelog

on:
  pull_request:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Changelog
        run: |
          echo "# Changelog" > changelog.md
          echo "" >> changelog.md
          git log --oneline origin/development..HEAD >> changelog.md

      - name: Commit and push changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add changelog.md
          git commit -m "Update changelog for pull request"
          git push
