name: Generate Changelog

on:
  pull_request:
    branches: [ master ]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Changelog
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { paginate } = require('@octokit/rest');
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = pr.base.ref; // Sollte jetzt "master" sein
            const head = pr.head.ref; // Sollte "development" sein

            // ... (Rest des Codes)
            await github.rest.repos.createOrUpdateFileContents({
              owner,
              repo,
              path: 'CHANGELOG.md',
              message: 'Update changelog',
              content: Buffer.from(changelog).toString('base64'),
              sha: 'master', // Schreibe in den master Branch
            });
